# Generated by Django 4.1.7 on 2023-03-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('number_phone', models.IntegerField(blank=True, verbose_name='Номер телефона')),
                ('organization', models.CharField(max_length=100, verbose_name='Название компании')),
            ],
        ),
    ]
