# Generated by Django 4.1.7 on 2023-03-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_post',
            name='delete_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher_post',
            name='success_check',
            field=models.BooleanField(default=False),
        ),
    ]
