# Generated by Django 4.1.7 on 2023-03-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_teacher_post_delete_post_teacher_post_success_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_post',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
